<a href="https://colab.research.google.com/github/US7103/MachinLearning-DataScience/blob/main/first.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
np.array([[2,3],[5,7]])

array([[2, 3],
       [5, 7]])

In [9]:
am=np.sum([[1,4],[4,9]])
am

np.int64(18)

In [13]:
np.zeros([5,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])